export const profile = {
  name: "Anchal Rathi",
  positioning: "Digital Marketing & Data Analytics",
  location: "Paris, France",
  email: "anchal.rathi@grenoble-em.com",
  linkedin: "https://www.linkedin.com/in/anchal-rathi-680802141",
  linkedinLabel: "linkedin.com/in/anchal-rathi-680802141",
  cv: "/Anchal_Rathi_CV.pdf",
  portrait: "/images/anchal-profile.jpg",
};

export const nav = [
  { label: "Introduction", href: "#introduction" },
  { label: "Experience", href: "#experience" },
  { label: "Skills", href: "#skills" },
  { label: "Education", href: "#education" },
  { label: "Contact", href: "#contact" },
];

export const intro = {
  label: "Introduction",
  headline: "I work at the intersection of marketing, technology and data.",
  subline: "Marketing & Sales professional — SEO, CRM, website development and analytics.",
  paragraphs: [
    "I am a Marketing and Sales professional with over two years of experience in digital marketing, SEO, PPC, CRM, website development and data analytics. Throughout my experience, I have worked across multiple areas of the digital marketing ecosystem, including building and optimising websites, managing CRM systems, executing marketing campaigns, improving search visibility and analysing performance data to support business growth.",
    "Most recently, I completed a five-month Marketing Internship at Latina S.A.M. in Monaco, where I designed and built the company's website on Shopware, worked on SEO initiatives, managed HubSpot CRM and marketing campaigns, supported LinkedIn content and contributed to marketing performance reporting and dashboard development.",
    "My experience has helped me develop a strong understanding of how marketing, technology and data work together to improve digital performance, strengthen customer engagement and support measurable business results.",
  ],
  facts: ["Paris, France", "Digital Marketing & Data Analytics", "Open to opportunities"],
};


export const experienceIntro = {
  label: "01 / Experience",
  heading: "What I have worked on so far.",
  text: "My experience spans website development, SEO, CRM, campaign management, data analytics, LinkedIn marketing and business development across different industries and business contexts.",
  closingQuote:
    "My experience has taught me to look at marketing as a connected system — website, search, CRM, content, campaigns and data all influence one another.",
};


export const latina = {
  company: "Latina S.A.M.",
  location: "Monaco",
  role: "Marketing Intern",
  dates: "April 2026 — August 2026",
  opening:
    "At Latina S.A.M., I worked across digital marketing, website development, CRM and marketing analytics. My role involved building the company's digital presence, improving online visibility, managing CRM campaigns, analysing marketing performance and supporting B2B communication.",
  website: "https://latina-mc.shock01.fridaycloud.nl/",
  sitemap: [
    "Home",
    "About",
    "Our Story",
    "Products",
    "Sourcing",
    "Distribution",
    "Markets",
    "Partners",
    "Contact",
  ],
  responsibilities: [
    "Website structure and information architecture",
    "Page layout development",
    "Content hierarchy",
    "Navigation structure",
    "Corporate website content",
    "Product presentation",
    "Business and service pages",
    "B2B messaging",
    "Shopware implementation",
    "Responsive page structure",
    "SEO-friendly content structure",
    "Multi-language content coordination",
  ],
  languages: ["English", "French", "Spanish", "Italian"],
  seoWork: [
    "Keyword research",
    "On-page SEO",
    "Technical SEO",
    "Content optimisation",
    "Page titles",
    "Meta descriptions",
    "Keyword placement",
    "URL structure",
    "Heading hierarchy",
    "Internal linking",
    "Image alt text",
    "Page optimisation",
    "Keyword monitoring",
    "Search ranking analysis",
    "Competitor keyword research",
    "SEO performance tracking",
    "SEO-friendly website structure",
  ],
  crmFlow: ["CRM", "Segmentation", "Campaign", "Engagement", "Follow-up", "Analysis"],
  crmManagement: [
    "Contact and lead organisation",
    "Tracking client interactions",
    "Maintaining structured CRM information",
    "Supporting follow-up activity",
  ],
  campaignManagement: [
    "Creating marketing emails",
    "Creating promotional spot offers",
    "Sending campaigns to targeted contacts",
    "Monitoring campaign performance",
    "Reviewing opens and clicks",
    "Identifying stronger-performing offers",
  ],
  hubspotMetrics: [
    { value: "73 → 3,716", label: "Campaign email sends grew from 73 in April to 3,716 in June." },
    { value: "84.2%", label: "Highest weekly email open rate recorded." },
    { value: "124", label: "Opens received by a high-performing individual offer." },
    { value: "13", label: "Clicks generated by the top June campaign." },
  ],
  analyticsAreas: [
    "Campaign sends",
    "Open rates",
    "Clicks",
    "Top-performing campaigns",
    "Lead activity",
    "Follow-up activity",
    "Marketing engagement",
    "Website performance",
    "Campaign trends",
  ],
  linkedinWork: [
    "Planning LinkedIn content",
    "Creating B2B post ideas",
    "Writing post copy",
    "Planning content calendars",
    "Company communication",
    "Industry-related content",
    "Brand visibility",
    "Business-focused storytelling",
    "Supporting client outreach",
  ],
  contentThemes: [
    "Company & Team",
    "Industry Insights",
    "International Distribution",
    "Wine & Spirits",
    "Partnerships",
    "Events",
    "Supply Chain",
    "Business Updates",
  ],
};

export const firstMeridian = {
  company: "FirstMeridian Global Services Private Limited",
  location: "Noida, India",
  role: "Management Executive",
  dates: "July 2024 — July 2025",
  opening:
    "My role at FirstMeridian focused on lead generation, client acquisition, LinkedIn outreach, CRM management and business development.",
  leadGenText:
    "I used targeted LinkedIn outreach to identify and engage potential business clients, supporting the lead generation and conversion process.",
  responsibilities: [
    "Prospect research",
    "LinkedIn outreach",
    "Lead identification",
    "Lead qualification",
    "Client communication",
    "Follow-up",
    "CRM tracking",
    "Business development support",
    "Relationship building",
  ],
  metrics: [
    { value: "40", label: "Clients acquired through LinkedIn outreach" },
    { value: "16", label: "Clients converted" },
    { value: "+35%", label: "Revenue increase" },
    { value: "+50%", label: "Improvement in lead quality" },
    { value: "+30%", label: "Improvement in profit margins" },
  ],
  closing:
    "The role strengthened my understanding of how targeted outreach, structured follow-up and better lead qualification can contribute directly to commercial performance.",
  bizDev:
    "Supported lead generation and business development initiatives involving brands such as Estée Lauder, Amazon and Mokobara.",
};

export const ssBeverages = {
  company: "S.S. Beverages",
  location: "Delhi, India",
  role: "Digital Marketing Intern",
  dates: "January 2024 — June 2024",
  opening:
    "At S.S. Beverages, I worked across SEO and paid digital marketing, developing experience in both organic search optimisation and performance marketing.",
  organic: [
    "On-page SEO",
    "Off-page SEO",
    "Keyword research",
    "Technical SEO",
    "Content optimisation",
    "Backlink building",
    "Search visibility optimisation",
    "Organic traffic improvement",
  ],
  paid: [
    "PPC",
    "Google Ads",
    "Facebook Ads",
    "Campaign monitoring",
    "Traffic generation",
    "Campaign optimisation",
  ],
};

export const skillGroups = [
  {
    heading: "Digital Marketing",
    items: [
      "SEO",
      "SEM",
      "PPC",
      "Google Ads",
      "Facebook Ads",
      "Keyword Research",
      "On-page SEO",
      "Off-page SEO",
      "Technical SEO",
      "Digital Strategy",
    ],
  },
  {
    heading: "CRM & Growth",
    items: [
      "HubSpot CRM",
      "Email Marketing",
      "Marketing Campaigns",
      "Lead Management",
      "Campaign Reporting",
      "B2B Lead Generation",
      "LinkedIn Outreach",
      "Inside Sales",
      "Pre-sales",
      "Business Development",
    ],
  },
  {
    heading: "Website & Content",
    items: [
      "Shopware",
      "Website Development",
      "WordPress",
      "Website Structure",
      "Content Organisation",
      "Landing Pages",
      "LinkedIn Marketing",
      "B2B Content",
    ],
  },
  {
    heading: "Data & Analytics",
    items: [
      "Power BI",
      "Data Analysis",
      "Excel",
      "SQL",
      "Python",
      "Marketing Analytics",
      "Dashboard Development",
      "KPI Reporting",
    ],
  },
];

export const education = {
  label: "03 / Education",
  heading: "Building the analytical side of marketing.",
  institution: "Grenoble École de Management",
  degree: "MSc Digital Marketing & Data Analytics",
  qualification: "Bac+5",
  from: "2025",
  to: "2027",
  location: "France",
  description:
    "My MSc combines digital marketing strategy with the analytical and technical skills required to understand modern customer journeys and marketing performance.",
  supporting:
    "I am continuing to develop my skills in digital marketing, SEO, Power BI, SQL, Python and data-driven decision-making.",
  languages: ["English — C2", "French — B2"],
  certifications: [
    "Inside LVMH — Creation & Branding",
    "Inside LVMH — Operations & Supply",
    "Advanced Internet Marketing Training Program",
  ],
  achievements: [
    "NCC C Certificate",
    "District Gold Medal — Discus Throw",
    "National Silver Medal — Discus Throw",
  ],
};
